services:
  postgres:
    image: postgres:15.2
    restart: unless-stopped
    ports:
      - "16543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: "Browser123!"

volumes:
  postgres-data: {}